# Generated by Django 5.2.8 on 2026-05-02 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('categorie', models.CharField(choices=[('evenement', 'Événement phare'), ('academique', 'Académique'), ('publication', 'Publication'), ('nomination', 'Nomination'), ('initiative', 'Initiative')], default='autre', max_length=20)),
                ('extrait', models.TextField(max_length=400)),
                ('contenu', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='actualites/')),
                ('lieu', models.CharField(blank=True, help_text='Ex: Noépé, Togo', max_length=150)),
                ('date_pub', models.DateField()),
                ('publie', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-date_pub'],
            },
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('none', 'Membre ordinaire'), ('president', 'Président(e)'), ('vp', 'Vice-Président(e)'), ('sg', 'Secrétaire Général(e)'), ('tresorier', 'Trésorier(ière)'), ('programmes', 'Chargé(e) des Programmes'), ('comm', 'Communication'), ('relations', 'Relations Institutionnelles')], default='none', max_length=50)),
                ('promotion', models.PositiveIntegerField(help_text='Année de la promotion (ex: 2023)')),
                ('institution', models.CharField(max_length=200)),
                ('bio', models.CharField(blank=True, max_length=300)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='membres/')),
                ('actif', models.BooleanField(default=True)),
                ('niveau_etude', models.CharField(choices=[('licence', 'Licence'), ('master', 'Master')], max_length=50)),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['nom', 'role'],
            },
        ),
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('promotion', models.PositiveIntegerField(blank=True, null=True)),
                ('sujet', models.CharField(choices=[('adhesion', 'Adhésion'), ('partenariat', 'Partenariat / Collaboration'), ('ressources', 'Ressources / Publications'), ('share', 'Événement Share To Us'), ('autre', 'Autre demande')], default='autre', max_length=20)),
                ('message', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('type_doc', models.CharField(choices=[('guide', 'Guide pratique'), ('note', 'Note de politique'), ('recherche', 'Travail de recherche'), ('outil', 'Outil méthodologique'), ('rapport', "Rapport d'activités")], default='guide', max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='ressources/')),
                ('lien', models.URLField(blank=True, help_text='Lien si hébergé ailleurs')),
                ('publique', models.BooleanField(default=True, help_text='Faux = réservé aux membres')),
                ('date_ajout', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ressource',
                'verbose_name_plural': 'Ressources',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
