# Generated by Django 5.2.8 on 2026-05-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ukWebSite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagecontact',
            name='statut',
            field=models.CharField(choices=[('attente', 'En attente'), ('termine', 'Terminé')], default='attente', max_length=10),
        ),
        migrations.AddField(
            model_name='messagecontact',
            name='telephone',
            field=models.CharField(blank=True, help_text='Numéro WhatsApp', max_length=20),
        ),
    ]
