# Generated by Django 5.2.8 on 2026-05-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ukWebSite', '0004_messagecontact_auteur_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='nom',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='profiles/default-avatar.png', null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='prenom',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
