# Generated by Django 5.2.8 on 2026-05-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ukWebSite', '0005_profile_bio_profile_nom_profile_photo_profile_prenom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
